source 'https://github.com/CocoaPods/Specs.git'

target 'PXCamera', :exclusive => true do
  pod "PXCamera", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "PXCamera", :path => "../"


end
